language: node_js
before_script:
  - yarn boot
branches:
  only:
    - master
addons:
  firefox: 56.0
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.0
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
  directories:
    - node_modules
    - packages/react-instantsearch/node_modules
    - packages/react-instantsearch-theme-algolia/node_modules
env:
  global:
  - ARGOS_TOKEN=da82cbbe3add183c6adb18f5c61da515d9bf99dd

  # BUNDLESIZE
  - secure: l0CdetUt1XFFO7W6qdamf5XkMsk/lkFx0NY5hjfhiBgCDOa5HvD7JeUlSwszM6MkbRqU/x4zoh8DomtZ19OAwxVapfo83YeMWyOmrbj7xjmuZeaAqI0KIQTSCpMaWq1NgD4NFWrkRIezzOUsbH65OGgMyUUtz8CBz0oKcf4BNO3o1scqAgwLKDuH0b+KQbCruR4rZlsmIY7jRsOKOJk2FV8mFJscF7vaF0Wg8/pfN4MfCQC8qGiOxqqBImCWo3LdIPZmOXTcr/+yBYzIA3fHudrZw9pYMVAFeifuaOA4wW03IPHpN7ppOa3XMPdy5kbXnVQoCWPfWGTSEuCemw0AtP+9hwQPeZgMnl9Mh+/5sIL9K3almtpRMaiOyNQyNF4ZAqt+QMkaHJF5d2SXBJ0D+irG5sOWICjzK4BR+lPv7kkSnuvN+1+fVRrEqX2GhSqYRgoyJYi/HF38AUy1NDIdcJXVipP7luSSnl1DNrmgTmXE+L+WcXkYdM8N5e2lQNApGeQlTZGYOE+w1AHrW4ISfI/jUGSASVkpuHGQnIFC2gCGqSrnk0VVbMCHHbQdyazhKxn8jSenqf4IOx3bmWawlP51emTeKF9/sb/5k2KLqhcLohu0Nfa4sVKRuneadxiDzXBWl+QrgUSURdsGoMvx7vsUoOye7GDLc+VyFI3oxqA=
